### PR TITLE
Allow commit fragment after state saved

### PR DESCRIPTION
**Pull request by l0stpenguin**
If the camera is enabled while the app is going into background, the plugin crashes:
`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState`

Solution is to ignore the state loss in the event the enable camera call happens after the app is paused
https://stackoverflow.com/questions/14860239/checking-if-state-is-saved-before-committing-a-fragmenttransaction

More details on activity state:
https://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

### CODE REVIEW

**Comment by ombr** [comment]
@sc-nick is this something we do or should do on CameraX ?

**Comment by sc-nick** [comment]
@ombr I tested it and nothing crashed on camerax because camera is closed before

**Comment by sc-nick** [comment]
@ombr I tested it and nothing crashed on camerax because the camera is closed before

**Comment by dinitri-ragoo** [comment]
@ombr @azharbeebeejaun  est- ce qu'on pourrait merger celui la ? c'est l'issue du savedInstance exception

**Pull request merged**
